### ISSUE TITLE
مشکل من با جکیل

### ISSUE THREAD

**Issue by biomanw** [theskn/Feedback#1]
سلام این مشکل نمایش متن راست به چپ رو چطور برطرف کنم؟

**Comment by theskn** [comment]
سلام،
.rtl-direction {
    direction: rtl;
}
این دقیقا کلاسیه که تو فایل‌های cssم تعریف میکنم و داخل html این کلاس رو به هر tagی که قصد راست چین کردنش رو داشته باشم، assign می‌کنم.
